---
- hosts: localhost
  tasks:
    - name: Install OpenJDK (used by elasticsearch)
      homebrew_cask:
        name: adoptopenjdk
        state: present
    - name: Install system services
      homebrew:
        name:
          - elasticsearch
          - memcached
          - mysql@5.7
          - redis@3.2
        state: present
    - name: Install runtime dependencies
      homebrew:
        name:
          - imagemagick@6
        state: present
    - name: Ensure memcached is running
      command: brew services restart memcached
    - name: Ensure MySQL is running
      command: brew services restart mysql@5.7
    - name: Ensure Redis is running
      command: brew services restart redis@3.2
